orc.app.daemon: true
orc.app.outfile: /tmp/server.log
orc.app.errfile: /tmp/server.log

servers:
 - svr.name: HelloServer
   svr.port: 8198
   svr.session.pool.size: 500
   svr.service.discovery: 101.201.148.9:2181/model1
   svr.workflow.pool.mode: singleton
   svr.workflow.file: /tmp/workflow.conf
   svr.handler.file: /tmp/handler.yaml
   svr.session.factory: HelloSessionFactory
   svr.workflow.router: HelloWorkflowRouter 

